defaults: &DEFAULTS
    access_key_id: "AKIAIB2PQYR2LSGIG4BA"
    secret_access_key: "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"
development:
    <<: *DEFAULTS
    bucket: "stagecoachlocal-assets"
test:
    <<: *DEFAULTS
    bucket: "stagecoachlocal-assets"
production:
    <<: *DEFAULTS
    bucket: "projectstagecoach-assets"